### PR TITLE
Update to storybook v7 API

### LINKED ISSUE #7: Incompatibility with `storyStoreV7`
Hi! 

Thanks for the great plugin! 🙏

FYI, I'm seeing an error when when storybook is configured to use `config.options.storyStoreV7`:

> Are you using a V6-style sort function in V7 mode?

When I remove the `storyStoreV7` storybook builds fine.

```
const config = {
  framework: '@storybook/react',

  core: {
    builder: 'webpack5',
  },

  features: {
    /** Configures Storybook to load stories on demand, rather than during boot up */
    storyStoreV7: true,
  },
};

export default config;
```

```
> start-storybook -p 6006 --no-open

info @storybook/react v6.5.14
info
info => Loading presets
info => Serving static files from ././.storybook/assets at /
info => Loading custom manager config
info Addon-docs: using MDX1
info => Using implicit CSS loaders
info => Using default Webpack5 setup
info => Loading custom manager config
/my-project/node_modules/@storybook/store/dist/cjs/sortStories.js:52
    throw new Error((0, _tsDedent.default)(_templateObject || (_templateObject = _taggedTemplateLiteral(["\n    Error sorting stories with sort parameter ", ":\n\n    > ", "\n    \n    Are you using a V6-style sort function in V7 mode?\n\n    More info: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#v7-style-story-sort\n  "])), storySortParameter, err.message));
          ^

Error: Error sorting stories with sort parameter (story1, story2) => sort(order, story1, story2):

> sort is not defined

Are you using a V6-style sort function in V7 mode?

More info: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#v7-style-story-sort
    at sortStoriesV7 (/my-project/node_modules/@storybook/store/dist/cjs/sortStories.js:52:11)
    at StoryIndexGenerator.sortStories (/my-project/node_modules/@storybook/core-server/dist/cjs/utils/StoryIndexGenerator.js:164:32)
    at StoryIndexGenerator.getIndex (/my-project/node_modules/@storybook/core-server/dist/cjs/utils/StoryIndexGenerator.js:178:18)
    at /my-project/node_modules/@storybook/core-server/dist/cjs/dev-server.js:117:24

Node.js v18.12.1
npm ERR! Lifecycle script `storybook` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @my-workspace@0.1.0
npm ERR!   at location: /my-project/apps/storybook
```

### PR DESCRIPTION
**Pull request by gatsbimantico**
It fixes https://github.com/prantlf/storybook-multilevel-sort/issues/7

### CODE REVIEW

**Comment by gatsbimantico** [comment]
There's information around the changes in their migration guide: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#v7-style-story-sort

**Review by diegoNutmeg — APPROVED** [review]
LGTM

**Comment by gatsbimantico** [comment]
This may still not work. Storybook seems to keep asking for the function to be inlined and fails to recognise the import of this library.

**Comment by prantlf** [comment]
Thank you for your contribution, @gatsbimantico! You did half of the work - the new documentation and adaptation to the new interface of `storySort`.

What remains is dealing with the new processing of the whole `preview.js`, which isn't an executable JavaScript module any more. It's just a source of an exported objects, which appears to be just parsed out of it. I'm going to write more about it to the issue #8.

You got this error, because you cannot refer to any external code out of the `storySort` callback:

```
ERR! Error: Error sorting stories with sort parameter (story1, story2) => sort(order, story1, story2):
ERR!
ERR! > sort is not defined
ERR!
ERR! Are you using a V6-style sort function in V7 mode?
```

The function `sort` and variable `order` from the sample project don't exist in the code, where the `storySort` implementation is injected.

I'm sorry, I'm not going to merge your changes. But my pull request #10 uses the fix that you found. I'm adding you to the package contributors too.

**Comment by prantlf** [comment]
This change is included and extended in #10.

**Pull request closed without merging**
